FROM buildpack-deps:xenial

RUN set -ex; \
	echo "deb http://archive.ubuntu.com/ubuntu/ xenial multiverse" >> /etc/apt/sources.list && \
	echo "deb-src http://archive.ubuntu.com/ubuntu/ xenial multiverse" >> /etc/apt/sources.list && \
	apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get install -y vim htop tree tmux sudo bash-completion ttf-mscorefonts-installer apt-utils && \
	git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git /opt/depot_tools

ENV PATH="$PATH:/opt/depot_tools"
